# Generated by Django 5.2.6 on 2025-09-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomemodels',
            name='amount',
            field=models.PositiveBigIntegerField(),
        ),
    ]
